package com.dhimsea.dbook.core.designsystem

import androidx.compose.ui.graphics.Color

// Light
val LightPrimary = Color(0xFF1A73E8)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD3E3FD)
val LightOnPrimaryContainer = Color(0xFF041E49)
val LightSecondary = Color(0xFF5F6368)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFE8EAED)
val LightOnSecondaryContainer = Color(0xFF1F1F1F)
val LightTertiary = Color(0xFF188038)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightBackground = Color(0xFFFFFFFF)
val LightOnBackground = Color(0xFF1F1F1F)
val LightSurface = Color(0xFFF8F9FA)
val LightOnSurface = Color(0xFF1F1F1F)
val LightSurfaceVariant = Color(0xFFE8EAED)
val LightOnSurfaceVariant = Color(0xFF5F6368)
val LightOutline = Color(0xFFDADCE0)

// Dark
val DarkPrimary = Color(0xFF8AB4F8)
val DarkOnPrimary = Color(0xFF041E49)
val DarkPrimaryContainer = Color(0xFF1A3A6B)
val DarkOnPrimaryContainer = Color(0xFFD3E3FD)
val DarkSecondary = Color(0xFF9AA0A6)
val DarkOnSecondary = Color(0xFF1F1F1F)
val DarkSecondaryContainer = Color(0xFF3C4043)
val DarkOnSecondaryContainer = Color(0xFFE8EAED)
val DarkTertiary = Color(0xFF81C995)
val DarkOnTertiary = Color(0xFF1F1F1F)
val DarkBackground = Color(0xFF1F1F1F)
val DarkOnBackground = Color(0xFFE8EAED)
val DarkSurface = Color(0xFF2D2D2D)
val DarkOnSurface = Color(0xFFE8EAED)
val DarkSurfaceVariant = Color(0xFF3C4043)
val DarkOnSurfaceVariant = Color(0xFF9AA0A6)
val DarkOutline = Color(0xFF5F6368)